main_app/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
import django_eventstream

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('rules/', views.rules, name='rules'),
    path('add_game/', views.add_game, name='add_game'),
    path('setup_game', views.setup_game, name='setup_game'),
    path('events/<str:room_name>/', views.generate_board, name='generate_board'),
    #url(r'^events/(?P<channel>\w+)/', include(django_eventstream.urls), {'format-channels': ['{channel}']}),
    path('game/<str:room_name>/', views.generate_board, name='generate_board'),
    path('game/<str:room_name>/actions', views.generate_actions, name='generate_actions'),
    path('game/<str:room_name>/next', views.push_next_stage, name='push_next_stage'),
    path('hand/rob/', views.hand_rob, name='hand_rob'),
    path('hand/<str:room_name>/vote/', views.hand_vote, name='hand_vote'),
    path('hand/<str:room_name>/voted/<int:voted_id>', views.hand_voted, name='hand_voted'),
    path('hand/<str:hand_id>/', views.hand_reveal, name='hand_reveal'),
    path('accounts/signup/', views.signup, name='signup'),
    path('profile/<int:user_id>/<int:profile_id>/add_photo/', views.add_photo, name='add_photo'), 
    path('profile/<int:user_id>/', views.profile, name='profile'), 
    path('rooms/<str:room_name>/', views.room, name='room'), 
]

#With profile now created we will need to either redirect user to the profile upon signup and/or have a button on the navbar for user. I advocate for both.

#need to add forms to templates

prayforsunrise/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User


STAGES = (
    ('1', 'SETUP', ),
    ('2', 'See Cards'),
    ('3', 'Werewolf'),
    ('4', 'Seer'),
    ('5', 'Seer Reveals'),
    ('6', 'Robber'),
    ('7', 'Troublemaker'),
    ('8', 'Drunk'),
    ('9', 'Day'),
    ('99', 'Complete')
)

ROLES = (
    ('V', 'Villager'),
    ('W', 'Werewolf'),
    ('T', 'Tanner'),
    ('S', 'Seer'),
    ('V', 'Villager'),
    ('R', 'Robber'),
    ('M', 'Troublemaker'),
    ('D', 'Drunk')
)

STATUS = (
    ('A', 'Alive'),
    ('E', 'Executed'),
    ('M', 'Murdered'),
    ('C', 'Consumed')
)

class Card(models.Model):
    imgurl = models.CharField(max_length=200)
    #CharacterName
    name = models.CharField(max_length=20)
    #Description/Special Text
    description = models.TextField(max_length=250)

    role = models.CharField(
        # We're going to set the rounds to an ENUM for now
        # hard coding the night roles ATM but should probably
        # find a move flexible solution
        max_length=1,
        choices=ROLES,
        # We want to make sure we always default to Setup

        default=[0][0]
    )

    def __str__(self):
        return self.name

class Game(models.Model):
    #Host - many-to-one / many(games) can have the same one (host)

    host = models.ForeignKey(User, related_name="host", on_delete=models.CASCADE)

    #Each game will have many cards
    card = models.ManyToManyField(Card)

    #Room - should rooms be their own class or a list - and how many?
    #-Nathan Change to string to denote the game\room our sockets open
    room = models.CharField(max_length=100)

    #We will need a many to many field for Users in a game connection I think.
    user = models.ManyToManyField(User)

    #stage - functionality needed to make stages count += / however there is only one round in ONUW? Or are we wanting more rounds?/functional
    #round looks like a keyword going to change to 'stage'
    stage = models.CharField(
        # We're going to set the rounds to an ENUM for now
        # hard coding the night roles ATM but should probably
        # find a more flexible solution
        max_length=2,
        choices=STAGES,
        # We want to make sure we always default to Setup

        default=[0][0]
    )

class Hand(models.Model):
    #Every hand will need to belong to a Game and assign a player a card
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    # Every Hand belongs to a user
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    status = models.CharField(
        # We're going to set the player status to an ENUM 
        max_length=1,
        choices=STATUS,
        # We want to make sure we always default to Setup
        default=[0][0]
    )


class Profile(models.Model):
    bio = models.CharField(max_length=20)
    eaten = models.IntegerField(default=0)
    executed = models.IntegerField(default=0)
    status = models.IntegerField(default=0)
    puser = models.ForeignKey(User, on_delete=models.CASCADE)

class Photo(models.Model):
    image = models.CharField(max_length=200)
    puser = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

main_app/forms.py
from django.forms import ModelForm
from .models import Game

class GameForm(ModelForm):
    class Meta:
        model = Game
        fields = ['room']

class SetupGameForm(ModelForm):
    class Meta:
        model = Game
        fields = ['room']

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.cache import cache
from django.http import HttpResponse
from django.template.loader import render_to_string
from django_eventstream import send_event
from channels.db import database_sync_to_async

import uuid, random
import boto3
import collections


from .forms import GameForm, SetupGameForm
from .models import Profile, Game, Card, Hand, STAGES, Photo


S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'prayforsunrise'


V_STAGES = [t[0] for t in STAGES if t[0]]


#This should exist elsewhere
@database_sync_to_async
def game_clear_hands(game):
    try:
        success = Hand.objects.filter(game=game).delete()
    except:
        print(f'did we trigger? No')
        return(False)
    print(f'did we trigger? {success}')
    return(success)


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def rules(request):
    return render(request, 'rules.html')

@database_sync_to_async
def room(request, room_name):
    try:
        game = Game.objects.get(room=room_name)
        room_user = User.objects.get(pk=request.user.id)
        game.user.add(room_user)
        cache.add(room_name, ['00'])
    except:
        print(game)
        return redirect('/')
    hands = Hand.objects.filter(game=game)
    try:
        playerhand = Hand.objects.get(game=game, user=request.user)
    except:
        playerhand = {}
    print(f'playerhand is {playerhand}')
    return render(request, 'game/room.html', {
        'room_name': room_name,
        'game': game,
        'hands': hands,
        "loser": "loser",
        "playerhand": playerhand
    })


def profile(request, user_id):
    profile = Profile.objects.get(puser=user_id)
    image = ''
    
    try:
        image = Photo.objects.get(profile=profile.id)
        print('image is,', image)

    except:
        print('No Photo Found')

    print('this is PROFILE', profile)
    print('this is user_id', user_id)
    return render(request, 'profile.html', {
        'profile': profile,
        'image': image
    })

### GAME FUNCTIONS

@database_sync_to_async
def add_game(request):
  form = GameForm(request.POST)
  new_room = ''
  if form.is_valid():
    new_game = form.save(commit=False)
    try:
        new_game.room = uuid.uuid4().hex[:4]
        new_game.host_id = request.user.id
        new_game.stage = STAGES[0][0]
        new_game.save()
        cache.add(new_game.room, ['00'])
        new_room = '/rooms/' + new_game.room
    except:
        print('An Error has occured generating your room')
    
  else:
      print(f'{form}')
  return redirect(new_room)

@database_sync_to_async
def setup_game( request ):
    form = SetupGameForm(request.POST)
    if form.is_valid():
        update_game=form.save(commit=False)
    start_game = Game.objects.get(room=update_game.room)
    index_of_stage = V_STAGES.index(start_game.stage)
    players = start_game.user.all()
    
    for player in players:
        print(f'{player} in {players}')
        new_hand = Hand()
        new_hand.game = start_game
        new_hand.user = player
        rand_card = random.choice(Card.objects.all())
        new_hand.card = rand_card
        new_hand.save()
    start_game.stage = STAGES[index_of_stage+1][0]
    start_game.save()

    print(f'send an SSE to {update_game.room}')
    send_event('gameroom', (update_game.room+'-updated'), {'text': 'board-updated'})
    #FIX: using a static room for SSE while we finish the game
    return redirect('rooms/' + update_game.room)


@database_sync_to_async
def push_next_stage(request, room_name):
    game = Game.objects.get(room=room_name)
    index_of_stage = V_STAGES.index(game.stage)
    
    #make sure we don't push past the last index
    if V_STAGES[index_of_stage] == V_STAGES[-1]:
        print(f'{index_of_stage}: index of current stage. {V_STAGES[-1]} is V_stages final item should be the 99')
        next_stage = STAGES[0][0]
        game_clear_hands(game)
    # elif V_STAGES[index_of_stage] == V_STAGES[8]:
    #     game_vote = cache.get(room_name)
    #     tally = collections.Counter(game_vote)
    #     loser = max(tally, key=game_vote.get)
    #     print(f'the loser is {loser}')

    else:
        next_stage = STAGES[index_of_stage+1][0]
    game.stage = next_stage
    game.save()
    send_event('gameroom', (game.room+'-updated'), {'text': 'board-updated'})
    return HttpResponse("Next Stage")


@database_sync_to_async
def generate_board(request, room_name):
    game = Game.objects.get(room=room_name)
    hands = Hand.objects.filter(game=game)
    loser = ''
    try:
        playerhand = Hand.objects.get(game=game, user=request.user)
    except:
        playerhand = {}
    game_vote = cache.get(room_name)
    print(f'the game_vote is {game_vote}')
    tally = collections.Counter(game_vote)
    print(f'the tally is {tally}')
    loser = max(tally, key=tally.get)
    print(f'the loser is {loser}')

    return render(request, "game/fragments/board.html", {
        "room_name":room_name,
        "hands":hands,
        "game":game,
        "playerhand":playerhand,
        "loser": loser,
        "request":request
        })


@database_sync_to_async
def generate_actions(request, room_name):
    game = Game.objects.get(room=room_name)
    print(f'This is our Game{game}, this is our room_name{room_name}')
    hands = Hand.objects.filter(game=game)
    try:
        playerhand = Hand.objects.get(game=game, user=request.user)
    except:
        playerhand = {}

    return render(request, "game/fragments/actions.html", {
        "room_name":room_name,
        "hands":hands,
        "game":game,
        "playerhand":playerhand,
        "loser": "loser",
        "request":request
        })


@database_sync_to_async
def hand_reveal(request, hand_id):
    hand = Hand.objects.get(id=hand_id)
    print(f'{request.user} revealed {hand.user} is a {hand.card}')
    # Return the card revealed by the seer here. 
    response = f'<li class="card" ic-get-from="/hand/{hand_id}"> <img src={hand.card.imgurl}> </li>'
    return render(request, "game/fragments/revealcard.html", {
        "hand":hand,
        "request":request
    })


@database_sync_to_async
def hand_rob(request):
    print(request.user)
    try:
        card = request.POST.get('card','')
    except:
        pass
    print(card)
    try:
        victim_hand = Hand.objects.get(id=card)
        player_hand = Hand.objects.get(user=request.user)
    except: 
        print('Robbery gone wrong')
    swaplist = [victim_hand.card.id, player_hand.card.id]
    print(swaplist)
    try:
        new_victim_card = Card.objects.get(id=swaplist[1])
        new_player_card = Card.objects.get(id=swaplist[0])
    except:
        pass
    player_hand.card = new_player_card
    victim_hand.card = new_victim_card
    victim_hand.save()
    player_hand.save()

    print(victim_hand.card.id)
    print(f'{request.POST}')
    return render(request, "game/fragments/revealcard.html", {
        "hand":player_hand,
        "request":request
    })


@database_sync_to_async
def hand_troublemaker(request):
    card_list = request.POST.getlist('card')

    return render(request, "game/fragments/revealcard.html", {
        "hand":player_hand,
        "request":request
    })


@database_sync_to_async
def hand_vote(request, room_name):
    print(request.user)
    try:
        card = request.POST.get('card','')
        card_list = request.POST.getlist('card')
    except:
        pass
    print(card_list)
    game = Game.objects.get(room=room_name)
    hands = Hand.objects.filter(game=game)
    try:
        playerhand = Hand.objects.get(game=game, user=request.user)
    except:
        playerhand = {}

    return render(request, "game/fragments/board.html", {
        "room_name":room_name,
        "hands":hands,
        "game":game,
        "playerhand":playerhand,
        "loser": "loser",
        "request":request
        })

@database_sync_to_async
def hand_voted(request, room_name, voted_id):
    print(request.user)
    try:
        game = Game.objects.get(room=room_name)
        playerhand = Hand.objects.get(game=game, user=request.user)
        hands = Hand.objects.filter(game=game)

    except:
        print("something went wrong")
        playerhand = {}
    game_vote = cache.get(room_name)
    print(game_vote)
    game_vote.append(voted_id)
    cache.set(room_name, game_vote)
    print(f'voted handid: {cache.get(room_name)}')

    game_vote = cache.get(room_name)
    print(f'the game_vote is {game_vote}')
    tally = collections.Counter(game_vote)
    print(f'the tally is {tally}')
    loser = max(tally, key=tally.get)
    print(f'the loser is {loser}')
    try:
        loser = Hand.objects.filter(id=loser)
    except:
        
        print("something went wrong")

    return render(request, "game/fragments/board.html", {
        "room_name":room_name,
        "hands":hands,
        "game":game,
        "playerhand":playerhand,
        "loser": loser,
        "request":request
        })

### OTHER PAGES    

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            profile = Profile(puser=user)
            profile.save()
            login(request, user)
            return redirect('/')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


def add_photo(request, user_id, profile_id):
    photo_file = request.FILES.get('photo-file', None)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}


<section class="about">\
    <div>
        <h1>About Pray For Sunrise</h1>
        <p class="white">Pray for Sunrise was developed by General Assembly Software Engineering Immerisve students <a
                href="https://github.com/NathanChildress">Nathan Childress</a>, <a
                href="https://github.com/Johnathanblackburncodes">Johnathan Blackburn</a>, and <a
                href="https://github.com/sweetvanloan">Sweet Van Loan</a> also known as "Team Werewolf". This game is
            based
            off
            of Bezier Games' "One Night Ultimate
            Werewolf", implementing the game logic in Django. </p>
        <br>
        <p class="white">Special thanks to Daniel Scott, Connnie Lancaster and David Schawel.</p>
        <br>
        <p class="white">Special thanks to EatVillagers. </p>
    </div>
</section>








{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>Pray for Sunrise</title>
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
  <link href="https://fonts.googleapis.com/css2?family=Metal+Mania&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/cards.css' %}" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript" src="{% static 'js/intercooler.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/sortable.js' %}"></script>
</head>

<body>
  <header class="navbar-fixed">
    <nav>
      <div class="container">
        <a class="logo" href="/">Pray for Sunrise</a>
        <ul class="right-nav">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'rules' %}">Rules</a></li>
          {% if user.is_authenticated %}


          <li><a href="{% url 'profile' user.id %}">Profile</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>
        <div class="menuWrap">
          <div id="mblIcon">
            <a id="hamb" href="#"></a>
          </div>
          <ul id="mobile">
            {% if user.is_authenticated %}

            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main>{% block content %} {% endblock %}</main>
  <footer class="page-footer">
    <div class="container">
      <div class="right">
        All Rights Reserved, &copy; 2020 Pray for Sunrise &nbsp;
      </div>
    </div>
  </footer>
  <script>
    $(function () {
      $('#mblIcon, #mobile').click(function () {
        $('#mobile a').toggleClass('vis');
        $('#mobile').slideToggle(600);
        $('#hamb').toggleClass('active');
      });
    });
  </script>
</body>

</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<section class="hero">
  <h1>Pray for Sunrise</h1>

  {% if user.is_authenticated %}

  <div class="game-selector">
    <h3>Which game room would you like to enter?</h3><br>
    <div class="room-btn">
      <input id="room-name-input" type="text"><br>
      <input id="room-name-submit" type="button" value="Enter">
    </div>
  </div>
  <h3>Create a game</h3><br>
  <div class="create-game-container">
    <form action="{% url 'add_game' %}" method="post">
      {% csrf_token %}
      {{  game_form.as_p }}
      <input type="hidden" name="room" id="id_room" value="newroom">
      <input type="submit" value="Add Game" class="btn">
    </form>
  </div>
  {% else %}
  <div>
    <h2 class="white">Pray for Sunrise is an game app inspired by Bezier Games One Night Ultimate Werewolf</h2><br>
    <h2 class="white">Artwork for Pray for Sunrise shared and copyright by <a href="https://www.eatvillagers.com/"
        target="_blank" rel="noopener noreferrer">Eat Villagers</a> </h2><br>
    <p class="white">Sign up or login to start playing with your friends!</p>
  </div>
  <ul class="btn-wrap">
    <li><a class="btn" href="{% url 'signup' %}">Sign Up</a></li>
    <li><a class="btn" href="{% url 'login' %}">Login</a></li>
  </ul>
  {% endif %}
</section>

{% if user.is_authenticated %}

<script>
  document.querySelector('#room-name-input').focus();
  document.querySelector('#room-name-input').onkeyup = function (e) {
    if (e.keyCode === 13) {  // enter, return
      document.querySelector('#room-name-submit').click();
    }
  };

  document.querySelector('#room-name-submit').onclick = function (e) {
    var roomName = document.querySelector('#room-name-input').value;
    window.location.pathname = '/' + 'rooms' + '/' + roomName + '/';
  };
</script>
{% endif %}

{% endblock %}

main_app/templates/profile.html
{% extends 'base.html' %}

{% block content %}

<div>
    <h1>{{ user.username }}</h1>
    <br><br>
    <p>{{ profile.bio }}</p>
    <br><br>
    <h1>Photo:</h1>
    <p>{{ profile.image }}</p>
    <img alt="Profile Image" src="{{ image.image }}">
    <br><br>
    <form action="{% url 'add_photo' user.id profile.id %}" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <input type="file" name="photo-file">
        <br><br>
        <input type="submit" value="Upload Photo">
    </form>
</div>

{% endblock %}

main_app/templates/rules.html
{% extends 'base.html' %}

{% block content %}
<section class="rules">
    <div class="container">
        <h1>Welcome to the Rules</h1>
        <p class="white">Here is where you can get an idea of how the game works!</p>
        <h2 class="white">You are a citizen of the village, but evil is afoot. While some of the players are mere
            villagers,
            some even
            purhaps
            with special abilities or traits, some are vile, evil, hungry werewolves ready to devour the entire village
            by
            midday! The villagers know that during this harrowing full moon, the werewolves will come for them. Thus the
            villagers go to bed, determined to stay alive come dawn knowing they will vote to execute suspected
            werewolves
            tomorrow morning. When the villagers all wake, some villagers with special powers may share what they have
            learned
            about their fellow villagers, but also, the werewolves will likely lie. For you see, no one can truly be
            fully
            trusted upon their word. Will the villagers prevail and destroy the werewolf scourge, or will the Werewolves
            have
            their long awaited meal? </h2>

        <div>
            <div class="rule">
                <h3 class="rule-heading red">Rule: Three Cards In the Middle.</h3>
                <p class="white">
                    Each User is given a card, describing their role. While three cards remain in the center. All other
                    cards
                    are discarded and thus not relevant to gameplay.
                </p>
            </div>
            <div class="rule">
                <h3 class="rule-heading red">Rule: The Witching Hour</h3>
                <p class="white">
                    Night comes to the village, with every villager keenly aware that at dawn they will vote to execute
                    a
                    suspected werewolf. During this time, some villagers with special powers may use their abilities to
                    find
                    out
                    who can be trusted and who must die. Each player with special abilities wakes at various points in
                    the
                    night
                    to perform their skill before going back to sleep to wait dawn. Any villager without a special
                    ability
                    will
                    remain asleep.
                </p>
            </div>
            <div class="rule">
                <h3 class="rule-heading red">Rule: The Final Countdown</h3>
                <p class="white">
                    There will be a timer counting down, starting from the moment dawn breaks and everyone in the
                    village
                    awaits. The village will convene and discuss who may be the cursed beasts to be put to death, or who
                    may
                    be
                    lying to save their own fur. Any villager with a special ability may or may not share what they are
                    and
                    what
                    they have done or learned. But be warned...not everyone is to be trusted at their word. When the
                    timer
                    is up
                    is it time to vote, no time to waste...time to execute a werewolf.
                </p>
            </div>
            <div class="rule">
                <h3 class="rule-heading red">Rule: The Vote</h3>
                <p class="white">
                    Each player will be given 1 single vote, make it count. During the time of voting, there is NO
                    TALKING
                    or
                    debating allowed. Whomever of the village receives the most votes is automatically assumed to be the
                    beast
                    and thus swiftly executed without further trial.
                </p>
            </div>
            <div class="rule">
                <h3 class="rule-heading red">Rule: The Villagers Win If...</h3>
                <p class="white">
                    The innocent Villagers win when at least one of the werewolves is executed OR if there are no
                    werewolves
                    and
                    no one dies.
                </p>
            </div>
            <div class="rule">
                <h3 class="rule-heading red">Rule: The Tanner Wins If...</h3>
                <p class="white">
                    The Tanner can only win one way, if they manage to convince the other players to execute them. If
                    the
                    Tanner
                    is execute, neither the Villagers nor the Werewolves win. Victory belongs only to the Tanner.
                </p>
            </div>
            <div class="rule">
                <h3 class="rule-heading red">Rule: The Werewolves Win If...</h3>
                <p class="white">
                    The Werewolves win when all the werewolves survive, and the Tanner does not die.
                </p>
            </div>
            <div class="rule">
                <h3 class="rule-heading red">Villager: The Drunk</h3>
                <p class="white">
                    The Drunk is a villager that wakes during the night once. The poor dear drank their troubles away
                    before
                    night had fallen and is so sauced that when they wake, they exhcange their card with 1 of the 3
                    cards in
                    the
                    center, but forgets to remember their new identity. The Drunk will never know that card, thus what
                    identity,
                    they now have. This will remain a mystery until the village has voted and someone is executed.
                </p>
            </div>
            <div class="rule">
                <h3 class="rule-heading red">Villager: The Seer</h3>
                <p class="white">
                    The Seer is a villager with special abilities - they wake during the night once. When the Seer wakes
                    up,
                    they can either look at a player's card, or 2 of the 3 cards in the center. The Seer may then use
                    that
                    knowledge come dawn to convince or dessuade others to vote for a particular villager.
                </p>
            </div>
            <div class="rule">
                <h3 class="rule-heading red">Villager: The Troublemaker</h3>
                <p class="white">
                    The Troublemaker is a villager with special abilities - they wake during the night once. When the
                    Troublemaker wakes they may switch 2 other player's cards, thus swapping said player's identities.
                    The
                    Troublemaker, however, has no idea what either card was and cannot swap their own card with another
                    player -
                    which is the role of the Robber.
                </p>
            </div>
            <div class="rule">
                <h3 class="rule-heading red">Villager: The Robber</h3>
                <p class="white">
                    Similar to the Troublemaker but not the same, the Robber is a villager with special abilities - they
                    wake
                    during the night once. When the Robber wakes, they may trade their card with another player. Also
                    unlike
                    the
                    Troublemaker, the Robber can view their new card once they receive it.
                </p>
            </div>
            <div class="rule">
                <h3 class="rule-heading red">NOTICE:</h3>
                <p class="white">
                    Know that during the night, anything could have happened. The Seer may have seen your card, The
                    Werewolves
                    know who each other are, the Drunk may have been in play and changed their card from one of the
                    cards in
                    the
                    middle, the Troublemaker could have swapped your card with another player, or the Robber could have
                    robbed
                    you, taking your card and taking your old identity, making you now the Robber.
                </p>
            </div>
            <div class="rule">
                <h3 class="rule-heading red">NOTICE: Regular Old Villagers</h3>
                <p class="white">
                    Sorry, buddy, but you have no special skills. When night falls, you sleep the full night and know
                    NOTHING of
                    what occured during the night.
                </p>
            </div>
        </div>
    </div>
</section>


{% endblock %}